// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaxH1RSkdAzEs7uso01Hh6wJPpGmhWYnc',
    appId: '1:654126609872:web:eb12adf066b3ee46d0f5d5',
    messagingSenderId: '654126609872',
    projectId: 'students-attendance-app-e9431',
    authDomain: 'students-attendance-app-e9431.firebaseapp.com',
    storageBucket: 'students-attendance-app-e9431.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8qqoXE0OkS28lV3bvoIFl0YbrtIJhy_k',
    appId: '1:654126609872:android:9a48d30e663d48e3d0f5d5',
    messagingSenderId: '654126609872',
    projectId: 'students-attendance-app-e9431',
    storageBucket: 'students-attendance-app-e9431.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkrlIoZYe4mBsmW-L7_qcJDubnCRg3KSA',
    appId: '1:654126609872:ios:1c133097423bba40d0f5d5',
    messagingSenderId: '654126609872',
    projectId: 'students-attendance-app-e9431',
    storageBucket: 'students-attendance-app-e9431.appspot.com',
    iosBundleId: 'com.example.studentsAttendanceManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkrlIoZYe4mBsmW-L7_qcJDubnCRg3KSA',
    appId: '1:654126609872:ios:0eda07f8bbd3a617d0f5d5',
    messagingSenderId: '654126609872',
    projectId: 'students-attendance-app-e9431',
    storageBucket: 'students-attendance-app-e9431.appspot.com',
    iosBundleId: 'com.example.studentsAttendanceManagementApp.RunnerTests',
  );
}
